### ISSUE TITLE
search_duration: 0, total_rows: 0 in all query responses

### ISSUE THREAD

**Issue by duhaime** [rnewson/couchdb-lucene#231]
Hello, I'm just getting started with couchdb-lucene, and am trying to figure out why all queries are yielding 0 hits. I'm running the master branch compiled on OSX, and my design document looks like this:

```
{
  "_id":"_design/card_design",
  "language": "javascript",
  "views": {
    "all_cards_by_wikipedia_page_id": {
      "map": "function(doc) { emit(doc.wikipedia_page_id, doc) }"
    },
    "all_cards_by_card_id": {
      "map": "function(doc) { if (doc._id)  emit(doc._id, doc) }"
    },
    "query_by_wikipedia_page_id": {
      "map": "function(doc) { if (doc.wikipedia_page_id)  emit(doc.wikipedia_page_id, doc) }"
    }
  },

  "lists": {
    "wikipedia_page_id_kv_store": "function(doc, req) { provides('json', function() { var results = {}; while(row = getRow()) { results[row.key] = row.value } send(JSON.stringify(results)); }) }"
  },

  "fulltext": {
    "by_bio": {
      "index":"function(doc) { var ret=new Document(); ret.add(doc.bio, {'field':'bio', 'type':'string', 'store':'yes', 'analyzer': 'keyword'}); log.info(doc.bio, ret); return ret }"
    }
  }
}
```

I can see the index exists, but when I query `http://localhost:5984/_fti/local/cards/_design/card_design_document/by_bio?q=film` (using film or any other word that appears in a bio) I get the following response:

```
{
q: "default:film",
fetch_duration: 0,
total_rows: 0,
limit: 25,
search_duration: 0,
etag: "1290afc361828",
skip: 0,
rows: [ ]
}
```

The strange thing is, my couchdb-lucene process is logging the bio from each "card" (as requested in the design document), but the logged `ret` object seems to be undefined:

```
2016-08-10 00:32:20,440 INFO [JSLog] Abner Benaim is a Panamanian film director, producer, screenwriter and plastic artist.
2016-08-10 00:32:20,441 INFO [JSLog] Brigitte Zarie is a Canadian-born American singer, songwriter and composer.
2016-08-10 00:32:20,442 INFO [JSLog] Cameron "Cam Kirk" Kirkland, is a photographer and videographer. Cam Kirk worked with and produced work for many hip hop artists such as Young Jeezy, T.I., Monica, 2 Chainz, Mike Will Made It, Estelle, Schoolboy Q, Future, Gucci Mane and many more.
2016-08-10 00:32:20,442 INFO [JSLog] undefined
2016-08-10 00:32:35,276 INFO [cards] View[name=_design/card_design_document/by_bio, digest=576qt9tixmmt8cp4pldonrsr7] now at update_seq 142
```

Am I missing something simple here? Any help you can offer would be very appreciated!

**Comment by duhaime** [comment]
@rnewson I wanted to send a polite bump to ask if you happen to have any insight on the thread above. If so, I'd certainly be grateful for your thoughts...

**Comment by rnewson** [comment]
hi, sorry. think I messed up my github notifications. looking into this now.

**Comment by rnewson** [comment]
ah, ok, I think it's easy. you indexed into a field called "bio" but you didn't specify it in your query. If you say ?q=film then we're searching in the default field (literally a field called "default", s ?q=default:film is equivalent).

Try ?q=bio:film

**Comment by rnewson** [comment]
(and I fixed my notification settings, sorry about the long silence. you can also use the couchdb user mailing list, other c-l users are there and so am I).

**Comment by duhaime** [comment]
Many thanks for your reply @rnewson! I tried `http://localhost:5984/_fti/local/cards/_design/card_design/by_bio?q=bio:film`, but get:

```
{
q: "bio:film",
fetch_duration: 0,
total_rows: 0,
limit: 25,
search_duration: 0,
etag: "66c09c2799ed",
skip: 0,
rows: [ ]
}
```

Is there something else I can check?

For what it's worth, when I run `curl 'localhost:5984/cards/_changes?feed=continuous&include_docs=true'` and then drop and create my 200 document database again, and submit the card_design document again, I see in the _changes shell only:

```
{"seq":239,"id":"_design/card_design","changes":[{"rev":"1-1b67bcd91812211f26e850e036f454ac"}],"doc":{"_id":"_design/card_design","_rev":"1-1b67bcd91812211f26e850e036f454ac","language":"javascript","views":{"all_cards_by_wikipedia_page_id":{"map":"function(doc) { emit(doc.wikipedia_page_id, doc) }"},"all_cards_by_card_id":{"map":"function(doc) { if (doc._id)  emit(doc._id, doc) }"},"query_by_wikipedia_page_id":{"map":"function(doc) { if (doc.wikipedia_page_id)  emit(doc.wikipedia_page_id, doc) }"},"keyword_search":{"map":"function(doc) {var txt = doc.plaintext; var words = txt.replace(/[!.,;]+/g,'').toLowerCase().split(' '); var addedWords = []; for (var word in words) { if (addedWords.indexOf(words[word]) == -1) {emit(words[word], doc)}; addedWords.push(words[word]);}}"}},"lists":{"wikipedia_page_id_kv_store":"function(doc, req) { provides('json', function() { var results = {}; while(row = getRow()) { results[row.key] = row.value } send(JSON.stringify(results)); }) }","search_results_by_wikipedia_page_id":"function(doc, req) { provides('json', function() { var results = {}; while(row = getRow()) { results[row.value.wikipedia_page_id] = row.value } send(JSON.stringify(results)); }) }"},"fulltext":{"by_bio":{"defaults":{"store":"yes"},"index":"function(doc) { var ret=new Document(); ret.add(doc.bio); return ret }"}}}}
```
I'd be grateful for any insights or thoughts you can send along.

**Comment by rnewson** [comment]
ok, do you have any documents where the field bio is exactly "film"? You've used the keyword analyzer, so you can only do exact matches on that field. If that's not your intention, the default analyzer ("standard") is fine. just remove the "analyzer":"keyword" from your design document (or specify "standard" explicitly.

**Comment by duhaime** [comment]
Thanks again @rnewson, but still no luck :/ Here's my full design doc:

```
{
  "_id":"_design/card_design",
  "language": "javascript",
  "views": {
    "all_cards_by_wikipedia_page_id": {
      "map": "function(doc) { emit(doc.wikipedia_page_id, doc) }"
    },
    "all_cards_by_card_id": {
      "map": "function(doc) { if (doc._id)  emit(doc._id, doc) }"
    },
    "query_by_wikipedia_page_id": {
      "map": "function(doc) { if (doc.wikipedia_page_id)  emit(doc.wikipedia_page_id, doc) }"
    },
    "keyword_search": {
      "map": "function(doc) {var txt = doc.plaintext; var words = txt.replace(/[!.,;]+/g,'').toLowerCase().split(' '); var addedWords = []; for (var word in words) { if (addedWords.indexOf(words[word]) == -1) {emit(words[word], doc)}; addedWords.push(words[word]);}}"
    }
  },

  "lists": {
    "wikipedia_page_id_kv_store": "function(doc, req) { provides('json', function() { var results = {}; while(row = getRow()) { results[row.key] = row.value } send(JSON.stringify(results)); }) }",
    "search_results_by_wikipedia_page_id": "function(doc, req) { provides('json', function() { var results = {}; while(row = getRow()) { results[row.value.wikipedia_page_id] = row.value } send(JSON.stringify(results)); }) }"
  },

  "fulltext": {
    "by_bio": {
      "index":"function(doc) { var ret=new Document(); ret.add(doc.bio, {'field':'bio', 'type':'string', 'store':'yes'}); log.info(doc.bio, ret); return ret }"
    }
  }

}
```

When I submit this and visit `http://localhost:5984/_fti/local/cards/_design/card_design/by_bio?q=bio:film`, I see:

```
{
q: "bio:film",
fetch_duration: 0,
total_rows: 0,
limit: 25,
search_duration: 0,
etag: "e06e4a3c211",
skip: 0,
rows: [ ]
}
```

When I visit `http://localhost:5984/_fti/local/cards/_design/card_design/by_bio` I get:

```
{
current: true,
doc_count: 239,
digest: "oonq819ho2hxf3xd9nqjgpwr",
update_seq: "239",
disk_size: 250464,
doc_del_count: 0,
fields: [
"bio"
],
ref_count: 2,
uuid: "8384a9f9-2389-4afa-be64-c95d7a736a51",
version: 5
}
```

and if I cd to `couchdb-lucene/target/couchdb-lucene-2.0.0-SNAPSHOT/indexes` (I'm on OSX) and `ls -lsh` I do indeed see the index:

```
ls -lsh
total 0
0 drwxr-xr-x  3 douglasduhaime  staff   102B Aug 15 21:15 1a2ba4bd-1705-4d95-b931-77083bcf6c04
0 drwxr-xr-x  3 douglasduhaime  staff   102B Aug 22 08:14 276020e2-b09a-45e0-b534-d1a9f437cdc9
0 drwxr-xr-x  3 douglasduhaime  staff   102B Aug 10 00:32 34616c71-2e99-4d37-9a51-f530b2a76790
0 drwxr-xr-x  3 douglasduhaime  staff   102B Aug 10 08:09 502fdab4-dcef-4000-8978-c5c1555d743b
0 drwxr-xr-x  3 douglasduhaime  staff   102B Aug 22 09:05 8384a9f9-2389-4afa-be64-c95d7a736a51
0 drwxr-xr-x  3 douglasduhaime  staff   102B Aug 15 21:32 b9cdf394-8c95-4ec5-af0d-a9ffc5e49339
0 drwxr-xr-x  3 douglasduhaime  staff   102B Aug 10 08:28 c62b5e8b-4e56-49c6-8415-27b01d79d7a4
0 drwxr-xr-x  3 douglasduhaime  staff   102B Aug 22 08:07 d4719db8-7235-45d1-a5b8-cbec0ba131f8
0 drwxr-xr-x  4 douglasduhaime  staff   136B Aug 15 21:04 f548e356-08c1-473f-82e0-b2e533612f04
```

The index (8384a9f9-2389-4afa-be64-c95d7a736a51) seems too small to contain the full tree structure--could there be something wrong with it? I'm grateful for your continued help!

**Comment by rnewson** [comment]
can you show me a full document, one that would match your query.

**Comment by rnewson** [comment]
and do a `du -sh couchdb-lucene/target/couchdb-lucene-2.0.0-SNAPSHOT/indexes/*` for a better look at index size.

**Comment by duhaime** [comment]
Sure thing--here's one:

```
{
  "bio": "Denice D. Lewis is an American former fashion model, actress, abstract artist, photographer, philanthropist and socialite. Following her modeling career, Lewis returned to America to further study visual arts in Hollywood including photography, fine art painting, and film making. She appeared as an actress in several films, including End of Days with Arnold Schwarzenegger, and television shows such as Red Shoe Diaries. After taking a break from public life, she now works as a creative entrepreneur and consultant in Los Angeles.",
  "plaintext": "Denice D. Lewis is an American former fashion model, actress, abstract artist, photographer, philanthropist and socialite. Following her modeling career, Lewis returned to America to further study visual arts in Hollywood including photography, fine art painting, and film making. She appeared as an actress in several films, including End of Days with Arnold Schwarzenegger, and television shows such as Red Shoe Diaries. After taking a break from public life, she now works as a creative entrepreneur and consultant in Los Angeles. As a model she was represented by various agencies including Wilhelmina, Models 1, Ford, and Elite Model Management. She appeared on a number of magazine covers, including Tatler and Town & Country. Alongside appearances in music videos such as Kiss and Tell by Brian Ferry, Slow Rivers by Elton John and Cliff Richard, and I'm Too Sexy by Right Said Fred; Lewis pursued an acting career in the 1990s. She landed various parts in episodes of the TV shows Red Shoe Diaries, Burke's Law (January 1994),[2] Silk Stalkings, and Renegade. She also appeared in films, including H.P. Lovecraft’s Necronomicon: Book of the Dead as the drowned wife,[3] Ed Wood’s I Woke Up Early the Day I Died, and as Arnold Schwarzenegger’s wife in End of Days. [4] In the early 2000s Lewis during a hiatus from public life became an abstract impressionist artist in Los Angeles, specializing in memorial paintings in which the ashes of the deceased are mixed with the pigment. [5] She was married to the late Al Seckel. [6] Denice Lewis Studios Website http://denicelewisstudios.com",
  "name": "Denice D. Lewis",
  "birth_date": "1960-11-28",
  "wikipedia_page_id": "45668778",
  "doc_vector": [
    -0.0177,
    0.3359,
    -0.1473,
    -0.016,
    0.0365,
    0.2312,
    -0.6669,
    -0.3306,
    -0.0997,
    0.1203,
    -0.0355,
    0.102,
    -0.3053,
    0.0728,
    0.4123,
    -0.2116,
    -0.1026,
    0.0497,
    -0.2649,
    -0.1086,
    0.2891,
    0.355,
    0.088,
    0.123,
    -0.0142,
    -0.943,
    -0.5033,
    -0.1653,
    -0.0772,
    -0.1158,
    2.1003,
    -0.1866,
    0.0659,
    -0.4589,
    0.0239,
    0.135,
    -0.0059,
    0.1525,
    -0.0999,
    -0.1806,
    0.0383,
    0.2278,
    -0.0495,
    -0.1952,
    -0.0386,
    -0.1055,
    -0.1363,
    -0.3995,
    -0.1413,
    0.2263
  ],
  "death_date": "",
  "page_views": 459,
  "thumbnail": "./assets/images/45668778.jpg",
  "wikipedia_page_name": "Denice_D._Lewis"
}
```
Thanks for the heads up that the indexes are multi-file.

**Comment by rnewson** [comment]
aah, I see now. change 'type' from 'string' to 'text'.

**Comment by duhaime** [comment]
WOOHOO! Thanks so much @rnewson What's the difference between string and text?

**Comment by rnewson** [comment]
a field of type string is like a keyword in older versions, it can only be matched as a whole.
a field of type text is broken up into words that can be searched individually.

I'll update the README to make this much clearer, I can see that it's not even documented. This is a fairly recent change as I upgraded from Lucene 4.x to 6.x and they made big changes (improvements) to typed fields.

**Comment by duhaime** [comment]
Nice, that sounds great. Thanks again for your help, this is working nicely! I'll close the issue.

**Comment by rnewson** [comment]
thanks! and sorry once again for the delay.

**Comment by duhaime** [comment]
No worries at all; I'm just glad you could help get this working! I would have never found the string -> text swap, and was starting to roll different vector based solutions. This will be much better for the searches I want to expose.
